### ISSUE TITLE
Automatic Builds for Windows

### ISSUE THREAD

**Issue by AnzoDK** [AnzoDK/PenguinTalk#2]
On Windows it's hard to compile both the client and the server - That needs to be addressed

**Comment by MagKon** [comment]
Solution - Split the project in to 3 parts.

1. Essentials: Everything except a source
2. Client: Import essentials and include the client source
3. Server: Import essentials and include the server source

**Comment by MagKon** [comment]
Fixed as of 0745def329b4c7520bc24269780aa2b0c82a4571
